// 常见 AI 服务商预设（OpenAI 兼容接口），供 GPT 参数设置里一键填充 url/model。
// url 填"基础地址"（后端会自动补 /chat/completions 或 /v1/chat/completions）。
// token 需到各家控制台自行申请，这里只给出获取入口链接，不内置任何密钥。
export const GPT_PROVIDERS = [
  {
    name: 'DeepSeek',
    url: 'https://api.deepseek.com',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    home: 'https://platform.deepseek.com',
    zh: '国内直连、性价比高，默认推荐',
    en: 'China-friendly, cost-effective, recommended default',
  },
  {
    name: 'OpenAI',
    url: 'https://api.openai.com/v1',
    models: ['gpt-4o-mini', 'gpt-4o', 'gpt-4.1'],
    home: 'https://platform.openai.com',
    zh: '官方 ChatGPT 接口，国内多需代理',
    en: 'Official ChatGPT API (may need a proxy in China)',
  },
  {
    name: 'Moonshot 月之暗面(Kimi)',
    url: 'https://api.moonshot.cn/v1',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'kimi-latest'],
    home: 'https://platform.moonshot.cn',
    zh: '长上下文见长',
    en: 'Strong long-context support',
  },
  {
    name: '智谱 GLM',
    url: 'https://open.bigmodel.cn/api/paas/v4',
    models: ['glm-4-flash', 'glm-4-air', 'glm-4-plus'],
    home: 'https://open.bigmodel.cn',
    zh: 'glm-4-flash 有免费额度',
    en: 'glm-4-flash offers a free tier',
  },
  {
    name: '通义千问 Qwen(阿里云)',
    url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    models: ['qwen-turbo', 'qwen-plus', 'qwen-max'],
    home: 'https://bailian.console.aliyun.com',
    zh: '阿里云百炼，兼容模式地址',
    en: 'Aliyun Bailian, OpenAI-compatible endpoint',
  },
  {
    name: '硅基流动 SiliconFlow',
    url: 'https://api.siliconflow.cn/v1',
    models: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-7B-Instruct'],
    home: 'https://siliconflow.cn',
    zh: '聚合多家开源模型，部分免费',
    en: 'Aggregates many open models, some free',
  },
  {
    name: '字节火山方舟(豆包)',
    url: 'https://ark.cn-beijing.volces.com/api/v3',
    models: ['填入你的接入点ID(endpoint id)'],
    home: 'https://console.volcengine.com/ark',
    zh: '模型名需填控制台创建的接入点 ID',
    en: 'Model name = the endpoint ID created in console',
  },
  {
    name: '百度千帆(文心)',
    url: 'https://qianfan.baidubce.com/v2',
    models: ['ernie-4.0-8k', 'ernie-speed-8k'],
    home: 'https://console.bce.baidu.com/qianfan',
    zh: '文心一言，v2 兼容接口',
    en: 'ERNIE, v2 compatible endpoint',
  },
  {
    name: '讯飞星火 Spark',
    url: 'https://spark-api-open.xf-yun.com/v1',
    models: ['4.0Ultra', 'generalv3.5'],
    home: 'https://xinghuo.xfyun.cn',
    zh: '讯飞星火开放接口',
    en: 'iFlytek Spark open API',
  },
  {
    name: 'OpenRouter',
    url: 'https://openrouter.ai/api/v1',
    models: ['deepseek/deepseek-chat', 'openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet'],
    home: 'https://openrouter.ai',
    zh: '一个 key 聚合全球众多模型',
    en: 'One key, hundreds of models worldwide',
  },
  {
    name: 'Groq',
    url: 'https://api.groq.com/openai/v1',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'],
    home: 'https://console.groq.com',
    zh: '推理速度极快，有免费额度',
    en: 'Very fast inference, free tier available',
  },
  {
    name: 'Ollama(本地)',
    url: 'http://localhost:11434/v1',
    models: ['qwen2.5', 'llama3.1', 'deepseek-r1'],
    home: 'https://ollama.com',
    zh: '本地私有部署，无需密钥(随便填)',
    en: 'Local self-host, token can be anything',
  },
  {
    name: 'one-api / new-api(自建聚合)',
    url: 'http://你的one-api地址/v1',
    models: ['按你在 one-api 里配置的渠道模型名'],
    home: 'https://github.com/songquanpeng/one-api',
    zh: '自建网关，统一管理多家渠道',
    en: 'Self-hosted gateway to manage multiple channels',
  },
];
